language:
  ruby

rvm:
  - '2.0'
  - '2.1'
  - '2.2'
  - '2.3.0'
  - '2.4.0'

script:
  - bundle exec rspec
  - bundle exec rubocop
  - gem env
  - gem list
  - ./bin/daru-view -g
  - ./bin/daru-view -H

install:
  - gem install bundler
  - gem install rainbow -v '2.2.1'
  - bundle install
